language: ruby
rvm:
  - 2.2

script: bundle exec jekyll build && htmlproofer ./_site

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
