language: ruby
rvm:
  - 2.3

gemfile: Gemfile.ci
script: bundle exec jekyll build && htmlproofer ./_site --check-html --allow-hash-href

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
