language: ruby
rvm:
  - 2.5.3
  
before_install:
  - gem install bundler

script: bundle exec jekyll build && htmlproofer ./_site --check-html --allow-hash-href

branches:
  only:
  - master
  
addons:
  apt:
    packages:
     - libcurl4-openssl-dev # required to avoid SSL errors
    
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
