name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'

      - name: install, build, test
        run: |
          gem install bundler
          bundle install
          bundle exec jekyll build && htmlproofer ./_site --check-html --allow-hash-href
        env:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer
