name: CI
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6
      volumes: 
        - my_docker_volume:/volume_mount
      env:
        LANG: C.UTF-8
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: install, build, test
        run: |
          gem install bundler
          bundle install --jobs 2 --retry 3
          JEKYLL_ENV=production bundle exec jekyll build
          htmlproofer ./_site --check-html --allow-hash-href --disable-external

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: develop # The branch the action should deploy from.
          BRANCH: master # The branch the action should deploy to.
          FOLDER: _site # The folder the action should deploy.
          
      - name: Success Notification
        uses: Ilshidur/action-discord@a7cda45617e36f767b67b6c69cbfa045641c8620
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: 'GoldbarGames/GoldbarGames.github.io has been successfully deployed'
          
