name: CI
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6
      env:
        LANG: C.UTF-8
    steps:
      - uses: actions/checkout@v1

      - name: install, build, test
        run: |
          gem install bundler
          bundle install
          JEKYLL_ENV=production bundle exec jekyll build
          htmlproofer ./_site --check-html --allow-hash-href --disable-external

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3-test
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: develop # The branch the action should deploy from.
          BRANCH: master # The branch the action should deploy to.
          FOLDER: _site # The folder the action should deploy.

