name: validate
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6
      env:
        LANG: C.UTF-8
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: install, test
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          SUCCESS_MESSAGE: "GoldbarGames/GoldbarGames.github.io has been successfully validated."
          ERROR_MESSAGE: "GoldbarGames/GoldbarGames.github.io failed to failed to validate. See https://github.com/GoldbarGames/GoldbarGames.github.io/actions?query=workflow%3Avalidate"
        run: |
          npm i -g axios && npm link axios
          gem install html-proofer
          htmlproofer ./ --check-html --http-status-ignore "403" --allow-hash-href || (DISCORD_MESSAGE=$ERROR_MESSAGE node ./discord.js && exit 1)
