name: validate
on:
  push:
    branches: 
      - master
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
          ref: master
          
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        
      - name: install, test
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          SUCCESS_MESSAGE: "GoldbarGames/GoldbarGames.github.io has been successfully validated"
          ERROR_MESSAGE: "GoldbarGames/GoldbarGames.github.io failed to failed to validate"
        run: |
          npm ci
          gem install html-proofer
          (htmlproofer ./ --check-html --allow-hash-href && DISCORD_MESSAGE=$SUCCESS_MESSAGE node ./discord.js) || DISCORD_MESSAGE=$ERROR_MESSAGE node ./discord.js
